(() => {
  'use strict';
  const modal=document.getElementById('chapterModal'),playBtn=document.getElementById('playBtn'),audioHint=document.getElementById('audioHint');
  class MenuAudio{
    constructor(){this.ctx=null;this.master=null;this.sfx=null;this.started=false;this.music=null;this.fallbackStarted=false;this.nodes=[]}
    startFallbackMusic(){if(this.fallbackStarted||!this.ctx)return;this.fallbackStarted=true;const now=this.ctx.currentTime,bus=this.ctx.createGain();bus.gain.value=(Number(localStorage.getItem('ls-ambience')||62)/100)*.12;bus.connect(this.master);this.nodes.push(bus);for(const [f,g,d] of [[43,.42,-6],[64.5,.18,5],[86,.08,-3]]){const o=this.ctx.createOscillator(),v=this.ctx.createGain();o.type='sine';o.frequency.value=f;o.detune.value=d;v.gain.value=g;o.connect(v).connect(bus);o.start(now);this.nodes.push(o,v)}}
    start(){if(this.started){this.ctx?.resume();this.music?.play().catch(()=>{});return}try{this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.sfx=this.ctx.createGain();this.master.gain.value=(Number(localStorage.getItem('ls-master')||80)/100)*.78;this.sfx.gain.value=Number(localStorage.getItem('ls-sfx')||78)/100;this.sfx.connect(this.master);this.master.connect(this.ctx.destination);this.music=new Audio();this.music.src=this.music.canPlayType('audio/ogg; codecs=vorbis')?'assets/audio/menu/menu-ambient.ogg':'assets/audio/menu/menu-ambient.mp3';this.music.loop=true;this.music.volume=Math.min(1,(Number(localStorage.getItem('ls-master')||80)/100)*(Number(localStorage.getItem('ls-ambience')||62)/100)*.68);this.music.play().catch(()=>this.startFallbackMusic());this.started=true;if(audioHint)audioHint.textContent='MENU AUDIO ACTIVE'}catch(_){this.startFallbackMusic()}}
    tone(freq=360,dur=.06,gain=.03,end=220){this.start();if(!this.ctx)return;const n=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='square';o.frequency.setValueAtTime(freq,n);o.frequency.exponentialRampToValueAtTime(end,n+dur);g.gain.setValueAtTime(gain,n);g.gain.exponentialRampToValueAtTime(.0001,n+dur);o.connect(g).connect(this.sfx);o.start(n);o.stop(n+dur)}
    hover(){this.tone(410,.045,.018,310)}click(){this.tone(160,.11,.042,80);setTimeout(()=>this.tone(520,.07,.024,300),35)}
  }
  const audio=new MenuAudio();document.addEventListener('pointerdown',()=>audio.start(),{once:true});
  function updateChapterStatus(){
    const oneComplete=localStorage.getItem('ls-night-one-complete')==='true'||localStorage.getItem('ls-chapter-01-complete')==='true';
    const oneStage=Math.max(0,Math.min(4,Number(localStorage.getItem('ls-night-one-stage')||0)));
    document.getElementById('chapterOneStatus').textContent=oneComplete?'COMPLETED':'AVAILABLE';document.getElementById('chapterOneCheckpoint').textContent=oneComplete?'REPLAY READY':oneStage>0?`CHECKPOINT ${oneStage}/4`:'NEW GAME';document.getElementById('chapterOnePlay').textContent=oneComplete?'REPLAY':'START';
    const twoComplete=localStorage.getItem('ls-night-two-complete')==='true'||localStorage.getItem('ls-chapter-02-complete')==='true';
    const twoStage=Math.max(0,Math.min(6,Number(localStorage.getItem('ls-night-two-stage')||0)));const card=document.getElementById('chapterTwoCard'),status=document.getElementById('chapterTwoStatus'),check=document.getElementById('chapterTwoCheckpoint'),play=document.getElementById('chapterTwoPlay');
    if(oneComplete){card.classList.remove('locked');card.classList.add('available');play.classList.remove('disabled');play.removeAttribute('aria-disabled');status.textContent=twoComplete?'COMPLETED':'AVAILABLE';check.textContent=twoComplete?'REPLAY READY':twoStage>0?`CHECKPOINT ${twoStage}/6`:'NEW CHAPTER';play.textContent=twoComplete?'REPLAY':'START'}else{card.classList.add('locked');card.classList.remove('available');play.classList.add('disabled');play.setAttribute('aria-disabled','true');status.textContent='LOCKED';check.textContent='COMPLETE CHAPTER 01';play.textContent='LOCKED'}
  }
  function open(){updateChapterStatus();modal.classList.remove('hidden');modal.setAttribute('aria-hidden','false')}function close(){modal.classList.add('hidden');modal.setAttribute('aria-hidden','true')}
  document.querySelectorAll('.menu-btn,.chapter-action,.close-chapters').forEach(el=>{el.addEventListener('pointerenter',()=>audio.hover());el.addEventListener('click',()=>audio.click())});playBtn.addEventListener('click',open);document.querySelectorAll('[data-close-chapters]').forEach(el=>el.addEventListener('click',close));document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});document.querySelectorAll('a[href]').forEach(a=>a.addEventListener('click',e=>{if(a.classList.contains('disabled')||a.getAttribute('aria-disabled')==='true'){e.preventDefault();return}if(a.target==='_blank'||e.metaKey||e.ctrlKey)return;e.preventDefault();const href=a.getAttribute('href');setTimeout(()=>location.href=href,85)}));updateChapterStatus();
})();
