(() => {
  'use strict';
  const defaults={master:80,sfx:78,ambience:62,graphics:'High',language:'en'},$=s=>document.querySelector(s),master=$('#master'),sfx=$('#sfx'),ambience=$('#ambience'),graphics=$('#graphics'),language=$('#language');
  const values={master:localStorage.getItem('ls-master')||defaults.master,sfx:localStorage.getItem('ls-sfx')||defaults.sfx,ambience:localStorage.getItem('ls-ambience')||defaults.ambience,graphics:localStorage.getItem('ls-graphics')||defaults.graphics,language:localStorage.getItem('ls-language')||defaults.language};
  master.value=values.master;sfx.value=values.sfx;ambience.value=values.ambience;graphics.value=values.graphics;language.value=values.language;$('#masterVal').value=values.master+'%';$('#sfxVal').value=values.sfx+'%';$('#ambienceVal').value=values.ambience+'%';
  function bind(i,o,k){i.addEventListener('input',()=>{o.value=i.value+'%';localStorage.setItem(k,i.value)})}bind(master,$('#masterVal'),'ls-master');bind(sfx,$('#sfxVal'),'ls-sfx');bind(ambience,$('#ambienceVal'),'ls-ambience');graphics.addEventListener('change',()=>localStorage.setItem('ls-graphics',graphics.value));language.addEventListener('change',()=>{localStorage.setItem('ls-language',language.value);$('#settingsNotice').textContent=language.value==='ar'?'تم اختيار العربية لكل فصول القصة.':'English selected for all story chapters.'});
  function update(){const c1=localStorage.getItem('ls-night-one-complete')==='true',c2=localStorage.getItem('ls-night-two-complete')==='true',s1=Number(localStorage.getItem('ls-night-one-stage')||0),s2=Number(localStorage.getItem('ls-night-two-stage')||0),coins=Number(localStorage.getItem('ls-coins')||0);$('#progressStatus').textContent=`CHAPTER 01: ${c1?'COMPLETED':s1?`CHECKPOINT ${s1}/4`:'NEW'} · CHAPTER 02: ${c2?'COMPLETED':s2?`CHECKPOINT ${s2}/6`:'NEW'} · ${coins} COINS`}
  $('#resetProgress').addEventListener('click',()=>{if(!confirm('Delete all saved chapter checkpoints and completion marks? Coins will be kept.'))return;['ls-night-one-stage','ls-night-one-complete','ls-chapter-01-complete','ls-night-two-stage','ls-night-two-complete','ls-chapter-02-complete'].forEach(k=>localStorage.removeItem(k));update();$('#settingsNotice').textContent='Chapter saves cleared. Coins were kept.'});update();
})();
