import * as THREE from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { clone as cloneSkeleton } from 'three/examples/jsm/utils/SkeletonUtils.js';

(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const canvas=$('gameCanvas'),loading=$('loading'),loadProgress=$('loadProgress'),loadText=$('loadText'),loadDetail=$('loadDetail');
  const storyGate=$('storyGate'),startStoryBtn=$('startStoryBtn'),cinematic=$('cinematic'),cinemaKicker=$('cinemaKicker'),cinemaTitle=$('cinemaTitle'),cinemaText=$('cinemaText'),cinemaFade=$('cinemaFade'),skipBtn=$('skipBtn'),skipCount=$('skipCount');
  const startOverlay=$('startOverlay'),enterGame=$('enterGame'),hud=$('hud'),objectiveText=$('objectiveText'),objectiveBar=$('objectiveBar'),subtitle=$('subtitle'),speaker=$('speaker'),subtitleText=$('subtitleText'),interactPrompt=$('interactPrompt'),interactText=$('interactText'),pointerHint=$('pointerHint');
  const healthBar=$('healthBar'),healthText=$('healthText'),staminaBar=$('staminaBar'),staminaText=$('staminaText'),ammoClip=$('ammoClip'),ammoReserve=$('ammoReserve'),reloadText=$('reloadText'),weaponName=$('weaponName'),missionState=$('missionState'),saveState=$('saveState'),damageFlash=$('damageFlash'),hitMarker=$('hitMarker'),alertBadge=$('alertBadge'),coinCount=$('coinCount');
  const pauseOverlay=$('pauseOverlay'),resultOverlay=$('resultOverlay'),inventoryOverlay=$('inventoryOverlay'),closeInventoryBtn=$('closeInventory'),inventoryShotgun=$('inventoryShotgun'),inventoryHatchet=$('inventoryHatchet'),bagAmmo=$('bagAmmo'),bagHealth=$('bagHealth'),bagCoins=$('bagCoins'),slotOneHud=$('slotOneHud'),slotTwoHud=$('slotTwoHud');

  const I18N={
    en:{
      gateKicker:'CHAPTER 02 · CINEMATIC AUDIO',gateTitle:'BEGIN NIGHT TWO',gateCopy:'Start the chapter to enable the car sequence, narration, hospital ambience, and story sound.',gateButton:'START CHAPTER',
      intro1:'Three hours after the first signal, the road north finally opened.',intro2:'The voice on the radio came from Saint Mercy Hospital.',intro3:'No rescue team returned from the building. You are going in alone.',arrival1:'The main entrance is blocked. An emergency light is still active inside.',arrival2:'Find the lower ward. That is where the signal originated.',
      startCopy:'The hospital is still drawing power from somewhere below. Find the source before the infected close in.',enter:'ENTER THE HOSPITAL',
      obj0:'Reach the reception hall',obj1:'Find the security keycard',obj2:'Restore emergency power',obj3:'Survive the containment breach',obj4:'Reach the underground records terminal',obj5:'Use the terminal to trace the signal',
      reception:'RECEPTION REACHED',keycard:'TAKE KEYCARD',generator:'START EMERGENCY POWER',terminal:'ACCESS TERMINAL',interact:'INTERACT',
      detected:'DETECTED',saved:'CHECKPOINT SAVED',remaining:'INFECTED REMAINING',shotgun:'TACTICAL SHOTGUN',hatchet:'OLD HATCHET',reload:'R TO RELOAD',reloading:'RELOADING…',melee:'MELEE · NO AMMO',noAmmo:'NO AMMO',
      survivor:'SURVIVOR',mara:'MARA',system:'HOSPITAL SYSTEM',sub0:'The lobby is too quiet. Keep the flashlight on.',sub1:'Reception is ahead. The keycard should be in the treatment wing.',sub2:'I found the card. The emergency generator is marked on the lower map.',sub3:'Power restored. Every locked door in the ward just opened.',sub4:'Containment failed. They are coming from the patient rooms.',sub5:'The ward is clear. The records terminal is beneath the west corridor.',sub6:'The hospital was used as a quarantine lab. The signal is coming from below the morgue.',
      complete:'LOWER WARD OPENED',completeText:'The hospital records reveal a sealed research level beneath Saint Mercy. The source of the outbreak is closer than anyone believed.',failed:'YOU DID NOT SURVIVE',failedText:'Saint Mercy claimed another survivor. Restart the chapter and keep moving.',
      loadingHospital:'Loading Saint Mercy Hospital…',loadingCar:'Preparing the arrival vehicle…',loadingInfected:'Loading new infected variants…',scanning:'Mapping hospital corridors…',ready:'Chapter Two ready'
    },
    ar:{
      gateKicker:'الفصل 02 · صوت المشهد',gateTitle:'ابدأ الليلة الثانية',gateCopy:'ابدأ الفصل لتشغيل مشهد السيارة وصوت القصة وأجواء المستشفى.',gateButton:'ابدأ الفصل',
      intro1:'بعد ثلاث ساعات من الإشارة الأولى، فُتح الطريق الشمالي أخيرًا.',intro2:'الصوت في الراديو جاء من مستشفى سانت ميرسي.',intro3:'لم يعد أي فريق إنقاذ من المبنى. ستدخل وحدك.',arrival1:'المدخل الرئيسي مغلق، لكن ضوء الطوارئ لا يزال يعمل بالداخل.',arrival2:'اعثر على الجناح السفلي، فمن هناك جاءت الإشارة.',
      startCopy:'المستشفى ما زال يسحب الكهرباء من مكان في الأسفل. اعثر على المصدر قبل أن يحاصرك المصابون.',enter:'ادخل المستشفى',
      obj0:'وصل إلى صالة الاستقبال',obj1:'اعثر على بطاقة الأمن',obj2:'أعد تشغيل كهرباء الطوارئ',obj3:'انجُ من اختراق جناح الحجر',obj4:'وصل إلى جهاز سجلات الطابق السفلي',obj5:'استخدم الجهاز لتتبع الإشارة',
      reception:'وصلت إلى الاستقبال',keycard:'خذ بطاقة الأمن',generator:'شغّل كهرباء الطوارئ',terminal:'استخدم جهاز السجلات',interact:'تفاعل',
      detected:'تم اكتشافك',saved:'تم حفظ نقطة التقدم',remaining:'المصابون المتبقون',shotgun:'بندقية تكتيكية',hatchet:'فأس قديم',reload:'اضغط R للتعمير',reloading:'جارٍ التعمير…',melee:'سلاح قريب · بدون ذخيرة',noAmmo:'لا توجد ذخيرة',
      survivor:'الناجي',mara:'مارا',system:'نظام المستشفى',sub0:'الردهة هادئة أكثر من اللازم. أبقِ الكشاف مضاءً.',sub1:'الاستقبال أمامك. يجب أن تكون بطاقة الأمن في جناح العلاج.',sub2:'وجدت البطاقة. مولّد الطوارئ ظاهر على خريطة الطابق السفلي.',sub3:'عادت الكهرباء. كل الأبواب المقفلة في الجناح فُتحت.',sub4:'فشل الحجر. إنهم يخرجون من غرف المرضى.',sub5:'الجناح آمن مؤقتًا. جهاز السجلات تحت الممر الغربي.',sub6:'استُخدم المستشفى كمختبر حجر. الإشارة قادمة من أسفل المشرحة.',
      complete:'فُتح الجناح السفلي',completeText:'تكشف سجلات المستشفى عن مستوى بحثي مغلق أسفل سانت ميرسي. مصدر الوباء أقرب مما ظن الجميع.',failed:'لم تنجُ',failedText:'ابتلع مستشفى سانت ميرسي ناجيًا آخر. أعد الفصل واستمر في الحركة.',
      loadingHospital:'جارٍ تحميل مستشفى سانت ميرسي…',loadingCar:'جارٍ تجهيز سيارة الوصول…',loadingInfected:'جارٍ تحميل أنواع المصابين الجديدة…',scanning:'جارٍ رسم ممرات المستشفى…',ready:'الفصل الثاني جاهز'
    }
  };
  let lang=localStorage.getItem('ls-language')||'en';const t=k=>I18N[lang]?.[k]||I18N.en[k]||k;

  const state={mode:'loading',stage:0,health:100,stamina:100,clip:8,reserve:48,weapon:'shotgun',reloading:false,axeSwinging:false,weaponSwitching:false,inventoryOpen:false,kills:0,shots:0,hits:0,coins:Number(localStorage.getItem('ls-coins')||0),chapterCoins:0,missionStart:0,lastShot:0,lastAttack:0,cinematicStart:0,cinematicFinished:false,gameEnded:false,detected:false,subtitleUntil:0,stepDistance:0,lastPosition:new THREE.Vector3(),checkpointShown:0};
  const keys=Object.create(null),zombies=[],coins=[],mixers=[],hospitalMeshes=[],walkPoints=[],objectivePoints=[];
  const loader=new GLTFLoader(),clock=new THREE.Clock(),raycaster=new THREE.Raycaster(),tmp=new THREE.Vector3(),tmp2=new THREE.Vector3(),centerRay=new THREE.Vector2();
  const templates={old:[],fresh:[],rifle:null,hatchet:null};let hospitalRoot=null,hospitalBox=new THREE.Box3(),hospitalFloorY=0,carRoot=null,carWheels=[];

  const renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.45));renderer.setSize(innerWidth,innerHeight,false);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.72;
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x040709);scene.fog=new THREE.FogExp2(0x060b0d,.021);
  scene.add(new THREE.HemisphereLight(0x8797a0,0x101315,.55));const moon=new THREE.DirectionalLight(0x8fa8bd,1.4);moon.position.set(-20,34,18);moon.castShadow=true;moon.shadow.mapSize.set(1024,1024);moon.shadow.camera.left=-50;moon.shadow.camera.right=50;moon.shadow.camera.top=50;moon.shadow.camera.bottom=-50;scene.add(moon);

  const player=new THREE.Object3D();scene.add(player);const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,280);camera.position.set(0,1.68,0);player.add(camera);let pitch=0;
  const cinematicCamera=new THREE.PerspectiveCamera(58,innerWidth/innerHeight,.1,400);scene.add(cinematicCamera);
  const bodyRoot=new THREE.Group();player.add(bodyRoot);const weaponRoot=new THREE.Group();camera.add(weaponRoot);let shotgunView=null,hatchetView=null;
  const flashlight=new THREE.SpotLight(0xe2efff,31,26,Math.PI/6.5,.52,1.3);flashlight.position.set(0,-.02,-.03);flashlight.castShadow=true;flashlight.shadow.mapSize.set(512,512);flashlight.shadow.bias=-.0005;flashlight.target.position.set(0,-.15,-7);camera.add(flashlight,flashlight.target);let flashlightOn=true;
  const marker=new THREE.Group();const diamond=new THREE.Mesh(new THREE.OctahedronGeometry(.22,0),new THREE.MeshBasicMaterial({color:0xd83941,transparent:true,opacity:.95}));const beam=new THREE.Mesh(new THREE.CylinderGeometry(.025,.14,2.8,10,1,true),new THREE.MeshBasicMaterial({color:0xc72d35,transparent:true,opacity:.16,side:THREE.DoubleSide,depthWrite:false}));beam.position.y=-1.4;marker.add(diamond,beam);scene.add(marker);

  class AudioEngine{
    constructor(){this.ctx=null;this.master=null;this.sfx=null;this.amb=null;this.buffers={};this.carNodes=[];this.cinemaNodes=[]}
    init(){if(this.ctx)return;try{this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.sfx=this.ctx.createGain();this.amb=this.ctx.createGain();this.master.gain.value=(Number(localStorage.getItem('ls-master')||80)/100)*.83;this.sfx.gain.value=Number(localStorage.getItem('ls-sfx')||78)/100;this.amb.gain.value=Number(localStorage.getItem('ls-ambience')||62)/100;this.sfx.connect(this.master);this.amb.connect(this.master);this.master.connect(this.ctx.destination);this.load();this.ambient()}catch(e){console.warn(e)}}
    resume(){if(this.ctx?.state==='suspended')this.ctx.resume()}
    async load(){const files={shotgun:'assets/audio/weapons/shotgun-fire.mp3',steps:'assets/audio/footsteps/footsteps.mp3',idle:'assets/audio/zombies/idle.mp3',attack:'assets/audio/zombies/attack.mp3',hurt:'assets/audio/zombies/hurt.mp3',generator:'assets/audio/environment/generator-start.mp3',radio:'assets/audio/environment/radio-static.mp3'};await Promise.all(Object.entries(files).map(async([k,p])=>{try{const r=await fetch(p);if(!r.ok)return;this.buffers[k]=await this.ctx.decodeAudioData(await r.arrayBuffer())}catch(_){}}))}
    play(name,volume=.5,rate=1,pan=0,offset=0,duration){if(!this.ctx||!this.buffers[name])return false;const s=this.ctx.createBufferSource(),g=this.ctx.createGain(),p=this.ctx.createStereoPanner?this.ctx.createStereoPanner():null;s.buffer=this.buffers[name];s.playbackRate.value=rate;g.gain.value=volume;if(p){p.pan.value=THREE.MathUtils.clamp(pan,-1,1);s.connect(g).connect(p).connect(this.sfx)}else s.connect(g).connect(this.sfx);const safeOffset=THREE.MathUtils.clamp(offset,0,Math.max(0,s.buffer.duration-.03));if(duration)s.start(0,safeOffset,Math.min(duration,Math.max(.03,s.buffer.duration-safeOffset)));else s.start(0,safeOffset);return true}
    osc(freq,dur,type='sine',gain=.04,end=0,bus=this.sfx){if(!this.ctx)return null;const n=this.ctx.currentTime,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,n);if(end)o.frequency.exponentialRampToValueAtTime(Math.max(20,end),n+dur);g.gain.setValueAtTime(gain,n);g.gain.exponentialRampToValueAtTime(.0001,n+dur);o.connect(g).connect(bus);o.start(n);o.stop(n+dur);return o}
    noise(dur=.1,gain=.04,cut=900,bus=this.sfx){if(!this.ctx)return;const len=Math.floor(this.ctx.sampleRate*dur),b=this.ctx.createBuffer(1,len,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<len;i++)d[i]=Math.random()*2-1;const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=cut;g.gain.setValueAtTime(gain,this.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,this.ctx.currentTime+dur);s.connect(f).connect(g).connect(bus);s.start()}
    ambient(){if(!this.ctx)return;const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sine';o.frequency.value=38;g.gain.value=.025;o.connect(g).connect(this.amb);o.start();const o2=this.ctx.createOscillator(),g2=this.ctx.createGain();o2.type='triangle';o2.frequency.value=57;g2.gain.value=.012;o2.connect(g2).connect(this.amb);o2.start()}
    startCar(){if(!this.ctx||this.carNodes.length)return;const bus=this.ctx.createGain();bus.gain.value=.09;bus.connect(this.amb);const o=this.ctx.createOscillator(),o2=this.ctx.createOscillator(),g=this.ctx.createGain();o.type='sawtooth';o2.type='triangle';o.frequency.value=72;o2.frequency.value=144;g.gain.value=.45;o.connect(g);o2.connect(g);g.connect(bus);o.start();o2.start();this.carNodes=[o,o2,g,bus];this.carOsc=o;this.carOsc2=o2}
    updateCar(speed){if(this.carOsc){this.carOsc.frequency.setTargetAtTime(58+speed*4.8,this.ctx.currentTime,.08);this.carOsc2.frequency.setTargetAtTime(116+speed*9.6,this.ctx.currentTime,.08)}}
    stopCar(){this.carNodes.forEach(n=>{try{n.stop?.()}catch(_){}try{n.disconnect?.()}catch(_){}});this.carNodes=[];this.carOsc=null;this.carOsc2=null}
    narrate(text){if(!('speechSynthesis'in window)||!text)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang==='ar'?'ar-EG':'en-US';u.rate=.88;u.pitch=.72;u.volume=.85;speechSynthesis.speak(u)}
    stopCinema(){this.stopCar();if('speechSynthesis'in window)speechSynthesis.cancel();this.cinemaNodes.forEach(n=>{try{n.stop?.()}catch(_){}try{n.disconnect?.()}catch(_){}});this.cinemaNodes=[]}
    step(sprint){if(this.play('steps',sprint?.5:.38,sprint?1.16:.98,0,Math.random()*12,.35))return;this.noise(.07,sprint?.055:.034,430);this.osc(68,.07,'sine',.016,48)}
    fire(){if(this.play('shotgun',.92,.98+Math.random()*.04))return;this.noise(.2,.18,1450);this.osc(82,.22,'sawtooth',.11,34)}
    reload(){this.osc(320,.05,'square',.025,210);setTimeout(()=>this.osc(430,.06,'square',.022,260),420)}
    empty(){this.osc(190,.05,'square',.025,110)}
    axe(){this.noise(.13,.06,820);this.osc(180,.12,'triangle',.035,90)}
    coin(){this.osc(660,.08,'sine',.05,940);setTimeout(()=>this.osc(990,.11,'sine',.04,1320),55)}
    objective(){this.osc(440,.1,'square',.035,660);setTimeout(()=>this.osc(660,.13,'square',.03,880),90)}
    groan(z,attack=false){const d=z.model.position.distanceTo(player.position),pan=Math.sin(Math.atan2(z.model.position.x-player.position.x,z.model.position.z-player.position.z)-player.rotation.y),vol=THREE.MathUtils.clamp(.85*(1-d/24),.12,.72);if(this.play(attack?'attack':'idle',vol,.86+Math.random()*.18,pan))return;this.osc(attack?74:48,.5,'sawtooth',vol*.08,28)}
    hurt(z,dying){const d=z.model.position.distanceTo(player.position),pan=Math.sin(Math.atan2(z.model.position.x-player.position.x,z.model.position.z-player.position.z)-player.rotation.y),vol=THREE.MathUtils.clamp(.9*(1-d/28),.12,.8);if(this.play('hurt',vol,dying?.78:.97,pan))return;this.osc(dying?42:70,.25,'sawtooth',vol*.08,30)}
    generator(){if(this.play('generator',.8))return;this.osc(48,.4,'sawtooth',.09,32);setTimeout(()=>this.osc(75,1.1,'sawtooth',.06,88),350)}
  }
  const audio=new AudioEngine();

  function setLanguage(next){lang=next;localStorage.setItem('ls-language',lang);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$('langBtn').textContent=lang==='en'?'EN / AR':'AR / EN';$('gateKicker').textContent=t('gateKicker');$('gateTitle').textContent=t('gateTitle');$('gateCopy').textContent=t('gateCopy');startStoryBtn.textContent=t('gateButton');$('startCopy').textContent=t('startCopy');enterGame.textContent=t('enter');updateObjective();updateHUD()}
  function showSubtitle(who,key,dur=3600){speaker.textContent=t(who);subtitleText.textContent=t(key);subtitle.classList.add('show');state.subtitleUntil=performance.now()+dur}
  function updateHUD(){healthBar.style.width=`${state.health}%`;healthText.textContent=Math.ceil(state.health);staminaBar.style.width=`${state.stamina}%`;staminaText.textContent=Math.ceil(state.stamina);ammoClip.textContent=state.weapon==='shotgun'?state.clip:'—';ammoReserve.textContent=state.weapon==='shotgun'?state.reserve:'—';weaponName.textContent=state.weapon==='shotgun'?t('shotgun'):t('hatchet');reloadText.textContent=state.weapon==='shotgun'?(state.reloading?t('reloading'):t('reload')):t('melee');coinCount.textContent=state.coins;slotOneHud.classList.toggle('active',state.weapon==='shotgun');slotTwoHud.classList.toggle('active',state.weapon==='hatchet');inventoryShotgun.classList.toggle('equipped',state.weapon==='shotgun');inventoryHatchet.classList.toggle('equipped',state.weapon==='hatchet');bagAmmo.textContent=`${state.clip} / ${state.reserve} rounds`;bagHealth.textContent=`${Math.ceil(state.health)} HEALTH`;bagCoins.textContent=`${state.coins} COINS`}
  function objectiveKey(){return['obj0','obj1','obj2','obj3','obj4','obj5'][Math.min(state.stage,5)]}
  function updateObjective(){if(!objectiveText)return;objectiveText.textContent=t(objectiveKey());objectiveBar.style.width=`${Math.min(100,(state.stage+1)/6*100)}%`;if(objectivePoints[state.stage]){marker.visible=true;marker.position.copy(objectivePoints[state.stage]);marker.position.y+=2.3}else marker.visible=state.stage<5}
  function saveCheckpoint(){localStorage.setItem('ls-night-two-stage',String(state.stage));saveState.textContent=t('saved');clearTimeout(saveCheckpoint.timer);saveCheckpoint.timer=setTimeout(()=>saveState.textContent='',2200)}

  function decodeBase64(base64){const raw=atob(base64),u=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)u[i]=raw.charCodeAt(i);return u.buffer}
  function loadGLB(path,label,progressStart,progressSpan){return new Promise(resolve=>loader.load(path,g=>resolve(g),p=>{if(p.total){const pct=Math.round(p.loaded/p.total*100);loadProgress.style.width=`${progressStart+pct/100*progressSpan}%`;loadText.textContent=`${label} ${pct}%`}},e=>{console.error(path,e);resolve(null)}))}
  function parseEmbedded(base64){return new Promise(resolve=>{if(!base64)return resolve(null);loader.parse(decodeBase64(base64),'',g=>resolve(g),e=>{console.error(e);resolve(null)})})}
  function normalizeObject(root,targetMax){root.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(root),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const s=targetMax/Math.max(size.x,size.y,size.z);root.scale.multiplyScalar(s);root.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(root);center=box.getCenter(new THREE.Vector3());root.position.x-=center.x;root.position.z-=center.z;root.position.y-=box.min.y;root.updateMatrixWorld(true);return new THREE.Box3().setFromObject(root)}

  function cleanScene(root,shadow=false){const remove=[];root.traverse(o=>{if(o.isLight||o.isCamera)remove.push(o);if(o.isMesh){o.castShadow=shadow;o.receiveShadow=true;o.frustumCulled=true}});remove.forEach(o=>o.parent?.remove(o))}
  function trackTargetName(name=''){const dot=name.lastIndexOf('.');let t=dot>=0?name.slice(0,dot):name;const slash=t.lastIndexOf('/');return slash>=0?t.slice(slash+1):t}
  function isolateTemplates(gltf,roots,kind){const templates=[];for(let i=0;i<roots.length;i++){const full=cloneSkeleton(gltf.scene),all=[];full.traverse(o=>{if(roots.some(n=>o.name===n))all.push(o)});const selected=full.getObjectByName(roots[i]);if(!selected)continue;all.forEach(o=>{if(o!==selected)o.parent?.remove(o)});selected.position.set(0,0,0);const names=new Set();selected.traverse(o=>{if(o.name)names.add(o.name)});const clips=(gltf.animations||[]).map((clip,j)=>{const tracks=clip.tracks.filter(tr=>{const target=trackTargetName(tr.name);if(!names.has(target))return false;if(target===selected.name&&/\.position$/i.test(tr.name))return false;return true}).map(tr=>tr.clone());return tracks.length?new THREE.AnimationClip(`${kind}_walk_${j}`,clip.duration,tracks):null}).filter(Boolean);full.updateMatrixWorld(true);let box=new THREE.Box3().setFromObject(full),size=box.getSize(new THREE.Vector3());if(size.y>.05){const s=1.82/size.y;full.scale.multiplyScalar(s);full.updateMatrixWorld(true);box=new THREE.Box3().setFromObject(full)}const wrap=new THREE.Group();wrap.add(full);full.position.y-=box.min.y;cleanScene(wrap,true);templates.push({scene:wrap,animations:clips,kind,name:roots[i]})}return templates}
  function prepareOld(gltf){const roots=[];gltf.scene.traverse(o=>{if(/^rig_CharRoot\d*$/.test(o.name))roots.push(o.name)});roots.sort();return isolateTemplates(gltf,roots,'old')}
  function prepareFresh(gltf){const group=gltf.scene.getObjectByName('GLTF_SceneRootNode');const roots=(group?.children||[]).map(o=>o.name).filter(Boolean);return isolateTemplates(gltf,roots,'fresh')}

  async function loadAssets(){
    loadText.textContent=t('loadingHospital');const hospitalG=await loadGLB('assets/models/abandoned-hospital.glb',t('loadingHospital'),4,48);if(!hospitalG)throw new Error('Hospital failed to load');hospitalRoot=hospitalG.scene;cleanScene(hospitalRoot,false);scene.add(hospitalRoot);hospitalBox=normalizeObject(hospitalRoot,74);hospitalRoot.traverse(o=>{if(o.isMesh){hospitalMeshes.push(o);if(o.material){const mats=Array.isArray(o.material)?o.material:[o.material];mats.forEach(m=>{if('metalness'in m)m.metalness=Math.min(m.metalness,.65);if('roughness'in m)m.roughness=Math.max(m.roughness,.34)})}}});
    loadText.textContent=t('loadingCar');const carG=await loadGLB('assets/models/survivor-car.glb',t('loadingCar'),52,10);if(carG){carRoot=carG.scene;cleanScene(carRoot,true);normalizeObject(carRoot,4.35);carRoot.traverse(o=>{if(/wheel/i.test(o.name))carWheels.push(o)});scene.add(carRoot)}
    loadText.textContent=t('loadingInfected');const [freshG,oldG,rifleG,hatchetG]=await Promise.all([loadGLB('assets/models/walking-dead-pack.glb',t('loadingInfected'),62,25),parseEmbedded(window.__ZOMBIE_PACK_BASE64__),parseEmbedded(window.__RIFLE_BASE64__),parseEmbedded(window.__HATCHET_BASE64__)]);if(freshG)templates.fresh=prepareFresh(freshG);if(oldG)templates.old=prepareOld(oldG);templates.rifle=rifleG;templates.hatchet=hatchetG;loadProgress.style.width='90%';
  }

  function sampleHospital(){loadText.textContent=t('scanning');hospitalRoot.updateMatrixWorld(true);const size=hospitalBox.getSize(tmp),maxY=hospitalBox.max.y+2,clusters=new Map(),raw=[];const step=2.2;raycaster.set(new THREE.Vector3(),new THREE.Vector3(0,-1,0));
    for(let x=hospitalBox.min.x+2;x<hospitalBox.max.x-2;x+=step){for(let z=hospitalBox.min.z+2;z<hospitalBox.max.z-2;z+=step){raycaster.ray.origin.set(x,maxY,z);raycaster.far=size.y+5;const hits=raycaster.intersectObjects(hospitalMeshes,false);for(const hit of hits){if(!hit.face)continue;const n=hit.face.normal.clone().transformDirection(hit.object.matrixWorld);if(n.y<.72||hit.point.y>hospitalBox.min.y+size.y*.58)continue;const key=Math.round(hit.point.y*2)/2;clusters.set(key,(clusters.get(key)||0)+1);raw.push({x,z,y:hit.point.y,key});break}}}
    let best=0,count=0;for(const [k,c] of clusters){if(c>count){count=c;best=k}}hospitalFloorY=best;for(const p of raw){if(Math.abs(p.y-best)>.55)continue;const pos=new THREE.Vector3(p.x,p.y+.05,p.z);let clear=true;for(const dir of [new THREE.Vector3(1,0,0),new THREE.Vector3(-1,0,0),new THREE.Vector3(0,0,1),new THREE.Vector3(0,0,-1)]){raycaster.set(pos.clone().add(new THREE.Vector3(0,.9,0)),dir);raycaster.far=.72;if(raycaster.intersectObjects(hospitalMeshes,false)[0]){clear=false;break}}if(clear)walkPoints.push(pos)}
    if(walkPoints.length<16){walkPoints.length=0;const y=hospitalBox.min.y+.08;for(let x=-18;x<=18;x+=4)for(let z=-9;z<=9;z+=3)walkPoints.push(new THREE.Vector3(x,y,z))}
    walkPoints.sort((a,b)=>b.z-a.z);const start=walkPoints[Math.floor(walkPoints.length*.1)]||walkPoints[0];player.position.copy(start);state.lastPosition.copy(player.position);const chosen=[start];while(objectivePoints.length<6){let bestP=null,bestD=-1;for(const p of walkPoints){const min=Math.min(...chosen.map(q=>q.distanceToSquared(p)));if(min>bestD){bestD=min;bestP=p}}if(!bestP)break;chosen.push(bestP);objectivePoints.push(bestP.clone())}while(objectivePoints.length<6)objectivePoints.push(start.clone().add(new THREE.Vector3((objectivePoints.length+1)*5,0,0)));buildEmergencyLights();
  }
  function buildEmergencyLights(){objectivePoints.forEach((p,i)=>{const light=new THREE.PointLight(i%2?0x5e8fb5:0xb72931,4.2,11,2);light.position.copy(p).add(new THREE.Vector3(0,2.5,0));scene.add(light);const lamp=new THREE.Mesh(new THREE.BoxGeometry(.25,.08,.25),new THREE.MeshStandardMaterial({color:0x25292b,emissive:i%2?0x31566e:0x72151a,emissiveIntensity:2.4}));lamp.position.copy(light.position);scene.add(lamp)})}

  function buildExterior(){const size=hospitalBox.getSize(tmp);const road=new THREE.Mesh(new THREE.PlaneGeometry(18,100),new THREE.MeshStandardMaterial({color:0x111517,roughness:.92,metalness:.04}));road.rotation.x=-Math.PI/2;road.position.set(0,.02,hospitalBox.max.z+45);scene.add(road);for(let i=0;i<18;i++){const line=new THREE.Mesh(new THREE.PlaneGeometry(.12,2.5),new THREE.MeshBasicMaterial({color:0x77745c}));line.rotation.x=-Math.PI/2;line.position.set(0,.035,hospitalBox.max.z+5+i*5.2);scene.add(line)}const fogCards=[];for(let i=0;i<28;i++){const m=new THREE.Mesh(new THREE.PlaneGeometry(4+Math.random()*8,1.2+Math.random()*2),new THREE.MeshBasicMaterial({color:0x87939a,transparent:true,opacity:.025+Math.random()*.035,depthWrite:false,side:THREE.DoubleSide}));m.position.set((Math.random()-.5)*28,.3+Math.random()*2,hospitalBox.max.z+Math.random()*90);m.rotation.y=Math.random()*Math.PI;scene.add(m);fogCards.push(m)}scene.userData.fogCards=fogCards;
    if(carRoot){carRoot.position.set(0,.05,hospitalBox.max.z+78);carRoot.rotation.y=Math.PI;const h1=new THREE.SpotLight(0xe7f2ff,18,35,Math.PI/8,.55,1.2),h2=h1.clone();h1.position.set(-.55,.65,-1.7);h2.position.set(.55,.65,-1.7);h1.target.position.set(-.55,.2,-15);h2.target.position.set(.55,.2,-15);carRoot.add(h1,h2,h1.target,h2.target)}}
  function buildBody(){bodyRoot.clear();const cloth=new THREE.MeshStandardMaterial({color:0x191d20,roughness:.95}),boot=new THREE.MeshStandardMaterial({color:0x0d0f10,roughness:.95});for(const s of [-1,1]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.105,.68,5,8),cloth);leg.position.set(s*.16,.48,.02);bodyRoot.add(leg);const foot=new THREE.Mesh(new THREE.BoxGeometry(.22,.15,.38),boot);foot.position.set(s*.16,.1,-.12);bodyRoot.add(foot)}}
  function viewMat(p){const m=new THREE.MeshStandardMaterial(p);m.depthTest=false;m.depthWrite=false;return m}
  function buildWeapons(){weaponRoot.clear();weaponRoot.position.set(.30,-.39,-.78);weaponRoot.userData.baseY=-.39;weaponRoot.userData.baseX=.30;weaponRoot.userData.baseZ=-.78;shotgunView=new THREE.Group();weaponRoot.add(shotgunView);const gun=viewMat({color:0x20262a,roughness:.32,metalness:.78}),grip=viewMat({color:0x15191b,roughness:.8}),wood=viewMat({color:0x5b2f1c,roughness:.8}),steel=viewMat({color:0x444b50,roughness:.38,metalness:.7}),skin=viewMat({color:0x76523f,roughness:.85});const receiver=new THREE.Mesh(new THREE.BoxGeometry(.13,.16,.62),gun);receiver.position.z=-.16;shotgunView.add(receiver);const barrel=new THREE.Mesh(new THREE.CylinderGeometry(.025,.034,.74,10),gun);barrel.rotation.x=Math.PI/2;barrel.position.set(0,.02,-.84);shotgunView.add(barrel);const stock=new THREE.Mesh(new THREE.BoxGeometry(.12,.16,.35),grip);stock.position.z=.3;shotgunView.add(stock);for(const s of [-1,1]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.065,.45,5,8),skin);arm.position.set(s*.19,-.17,-.2);arm.rotation.set(-1.1,0,s*.22);shotgunView.add(arm)}shotgunView.userData.muzzle=new THREE.PointLight(0xffad55,0,7,2);shotgunView.userData.muzzle.position.set(0,.03,-1.18);shotgunView.add(shotgunView.userData.muzzle);hatchetView=new THREE.Group();hatchetView.visible=false;weaponRoot.add(hatchetView);const handle=new THREE.Mesh(new THREE.CylinderGeometry(.035,.045,.82,10),wood);handle.rotation.z=Math.PI/2;handle.position.set(.02,-.02,-.22);hatchetView.add(handle);const head=new THREE.Mesh(new THREE.BoxGeometry(.25,.18,.09),steel);head.position.set(-.42,.02,-.22);hatchetView.add(head);const blade=new THREE.Mesh(new THREE.ConeGeometry(.14,.25,4),steel);blade.rotation.z=-Math.PI/2;blade.position.set(-.56,.02,-.22);hatchetView.add(blade);const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.067,.46,5,8),skin);arm.position.set(.3,-.3,.04);arm.rotation.set(-1.15,0,.38);hatchetView.add(arm);[shotgunView,hatchetView].forEach(v=>v.traverse(o=>{if(o.isMesh){o.renderOrder=12;o.castShadow=false;o.receiveShadow=false}}));setupImportedWeapons();applyWeapon()}
  function cleanView(root){root.traverse(o=>{if(o.isMesh){o.frustumCulled=false;o.renderOrder=12;o.castShadow=false;o.receiveShadow=false;if(o.material){const a=Array.isArray(o.material)?o.material:[o.material];const c=a.map(m=>{const n=m.clone();n.depthTest=false;n.depthWrite=false;return n});o.material=Array.isArray(o.material)?c:c[0]}}})}
  function setupImportedWeapons(){if(templates.rifle){try{const old=shotgunView,cand=new THREE.Group(),r=cloneSkeleton(templates.rifle.scene);cleanView(r);const box=new THREE.Box3().setFromObject(r),size=box.getSize(tmp),c=box.getCenter(tmp2),s=1.17/Math.max(size.x,size.y,size.z);r.scale.setScalar(s);r.position.set(-c.x*s,-c.y*s,-c.z*s);const wrap=new THREE.Group();wrap.rotation.y=Math.PI/2;wrap.position.set(0,.02,-.14);wrap.add(r);cand.add(wrap);const skin=viewMat({color:0x76523f,roughness:.85});for(const q of [[.21,-.27,-.02],[-.15,-.3,-.45]]){const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.06,.42,5,8),skin);arm.position.set(...q);arm.rotation.x=-1.13;cand.add(arm)}cand.userData.muzzle=new THREE.PointLight(0xffad55,0,8,2);cand.userData.muzzle.position.set(0,.04,-1.05);cand.add(cand.userData.muzzle);old.removeFromParent();shotgunView=cand;weaponRoot.add(cand)}catch(e){console.warn(e)}}if(templates.hatchet){try{const old=hatchetView,cand=new THREE.Group(),h=cloneSkeleton(templates.hatchet.scene);cleanView(h);const box=new THREE.Box3().setFromObject(h),size=box.getSize(tmp),c=box.getCenter(tmp2),s=.92/Math.max(size.x,size.y,size.z);h.scale.setScalar(s);h.position.set(-c.x*s,-c.y*s,-c.z*s);cand.position.set(.12,-.03,-.1);cand.rotation.set(-.16,.08,-.72);cand.add(h);old.removeFromParent();hatchetView=cand;weaponRoot.add(cand)}catch(e){console.warn(e)}}}
  function applyWeapon(){shotgunView.visible=state.weapon==='shotgun';hatchetView.visible=state.weapon==='hatchet';updateHUD()}
  function setViewVisible(v){weaponRoot.visible=v;bodyRoot.visible=v}

  function spawnZombieAt(pos,index=0,fresh=false,wave=false){const pool=fresh&&templates.fresh.length?templates.fresh:templates.old.length?templates.old:templates.fresh;const tpl=pool[index%Math.max(1,pool.length)];let model;if(tpl)model=cloneSkeleton(tpl.scene);else{model=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:fresh?0x6b4c46:0x60675e,roughness:.9});const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.3,.8,6,10),mat);torso.position.y=1.1;model.add(torso);const head=new THREE.Mesh(new THREE.SphereGeometry(.24,12,10),mat);head.position.y=1.78;model.add(head)}model.position.copy(pos);model.rotation.y=Math.random()*Math.PI*2;scene.add(model);const z={model,fresh,hp:fresh?190+Math.random()*90:95+Math.random()*35,maxHp:0,speed:fresh?1.65+Math.random()*.5:1.05+Math.random()*.35,damage:fresh?12+Math.floor(Math.random()*5):7+Math.floor(Math.random()*4),alive:true,alerted:wave,state:wave?'chase':'idle',lastAttack:0,nextGroan:performance.now()+800+Math.random()*2600,deathTime:0,coinDropped:false,mixer:null,action:null,wave};z.maxHp=z.hp;const idx=zombies.length;model.traverse(o=>{if(o.isMesh){o.userData.zombieIndex=idx;o.castShadow=true;o.receiveShadow=true}});if(tpl?.animations?.length){z.mixer=new THREE.AnimationMixer(model);z.action=z.mixer.clipAction(tpl.animations[0]);z.action.play();z.action.timeScale=fresh?1.18:.9;mixers.push(z.mixer)}zombies.push(z);return z}
  function spawnInitial(){const candidates=walkPoints.filter(p=>p.distanceTo(player.position)>8);for(let i=0;i<10;i++){const p=(candidates[(i*7+3)%Math.max(1,candidates.length)]||objectivePoints[(i+1)%objectivePoints.length]).clone();spawnZombieAt(p,i,i%3===0,false)}}
  function spawnWave(){const around=walkPoints.filter(p=>p.distanceTo(player.position)>6&&p.distanceTo(player.position)<24);for(let i=0;i<12;i++){const p=(around[(i*5+2)%Math.max(1,around.length)]||objectivePoints[(i+2)%objectivePoints.length]).clone();spawnZombieAt(p,i,true,true)}showSubtitle('system','sub4',4000);audio.objective()}

  function floorAt(x,z,currentY){raycaster.set(new THREE.Vector3(x,currentY+1.3,z),new THREE.Vector3(0,-1,0));raycaster.far=3.2;const hits=raycaster.intersectObjects(hospitalMeshes,false);for(const h of hits){if(!h.face)continue;const n=h.face.normal.clone().transformDirection(h.object.matrixWorld);if(n.y>.62)return h.point.y+.03}return currentY}
  function blocked(pos,dir,dist=.68){raycaster.set(pos.clone().add(new THREE.Vector3(0,1.0,0)),dir);raycaster.far=dist;return !!raycaster.intersectObjects(hospitalMeshes,false)[0]}
  function hasLineOfSight(a,b){const dir=b.clone().sub(a),d=dir.length();dir.normalize();raycaster.set(a,dir);raycaster.far=d;return !raycaster.intersectObjects(hospitalMeshes,false)[0]}
  function movePlayer(dt){const f=(keys.KeyW?1:0)-(keys.KeyS?1:0),s=(keys.KeyD?1:0)-(keys.KeyA?1:0),moving=Math.abs(f)+Math.abs(s)>0;const sprint=keys.ShiftLeft&&f>0&&state.stamina>2;state.stamina=THREE.MathUtils.clamp(state.stamina+(sprint?-31:moving?7:18)*dt,0,100);if(moving){const dir=new THREE.Vector3(s,0,-f).normalize().applyAxisAngle(new THREE.Vector3(0,1,0),player.rotation.y),speed=sprint?5.3:2.9;const xdir=new THREE.Vector3(dir.x,0,0),zdir=new THREE.Vector3(0,0,dir.z);if(Math.abs(xdir.x)>.01&&!blocked(player.position,xdir.clone().normalize(),.75))player.position.x+=xdir.x*speed*dt;if(Math.abs(zdir.z)>.01&&!blocked(player.position,zdir.clone().normalize(),.75))player.position.z+=zdir.z*speed*dt;player.position.x=THREE.MathUtils.clamp(player.position.x,hospitalBox.min.x+.5,hospitalBox.max.x-.5);player.position.z=THREE.MathUtils.clamp(player.position.z,hospitalBox.min.z+.5,hospitalBox.max.z-.5);player.position.y=floorAt(player.position.x,player.position.z,player.position.y);const d=player.position.distanceTo(state.lastPosition);state.stepDistance+=d;if(state.stepDistance>(sprint?.92:1.28)){audio.step(sprint);state.stepDistance=0}state.lastPosition.copy(player.position);const bob=Math.sin(performance.now()*(sprint?.013:.009))*(sprint?.025:.014);camera.position.y=1.68+bob;weaponRoot.position.y=weaponRoot.userData.baseY+bob*1.9;bodyRoot.children.forEach((o,i)=>{if(o.isMesh&&i<2)o.rotation.x=Math.sin(performance.now()*.009+i*Math.PI)*(sprint?.36:.22)})}else{camera.position.y=THREE.MathUtils.lerp(camera.position.y,1.68,dt*8);state.lastPosition.copy(player.position)}updateHUD()}

  function updateZombies(dt,now){let any=false;for(const z of zombies){if(!z.alive){const p=Math.min(1,(now-z.deathTime)/900);z.model.rotation.z=THREE.MathUtils.lerp(z.model.rotation.z,Math.PI*.48,p);z.model.position.y-=dt*.25;continue}const eye=z.model.position.clone().add(new THREE.Vector3(0,1.25,0)),target=player.position.clone().add(new THREE.Vector3(0,1.1,0)),d=eye.distanceTo(target);if(!z.alerted&&d<(z.fresh?15:11)&&hasLineOfSight(eye,target)){z.alerted=true;audio.groan(z,true)}if(z.alerted){any=true;const dir=target.clone().sub(eye);dir.y=0;const dist=dir.length();dir.normalize();z.model.rotation.y=Math.atan2(dir.x,dir.z);if(dist>1.35){if(!blocked(z.model.position,dir,.55)){z.model.position.addScaledVector(dir,z.speed*dt);z.model.position.y=floorAt(z.model.position.x,z.model.position.z,z.model.position.y)}else{const side=new THREE.Vector3(-dir.z,0,dir.x);if(!blocked(z.model.position,side,.5))z.model.position.addScaledVector(side,z.speed*.65*dt)}z.action&&(z.action.paused=false)}else if(now-z.lastAttack>1050){z.lastAttack=now;audio.groan(z,true);z.model.position.addScaledVector(dir,.16);damagePlayer(z.damage)}if(now>z.nextGroan){audio.groan(z,false);z.nextGroan=now+1800+Math.random()*3200}}else{z.model.rotation.y+=Math.sin(now*.0004+z.model.id)*dt*.15;if(now>z.nextGroan&&d<22){audio.groan(z,false);z.nextGroan=now+2600+Math.random()*4200}}}alertBadge.classList.toggle('show',any);state.detected=any;if(state.stage===3){const remain=zombies.filter(z=>z.alive&&z.wave).length;missionState.textContent=`${t('remaining')}: ${remain}`;if(remain===0){state.stage=4;missionState.textContent='';showSubtitle('mara','sub5',4200);saveCheckpoint();updateObjective()}}}
  function damagePlayer(amount){if(state.gameEnded)return;state.health=Math.max(0,state.health-amount);damageFlash.classList.add('show');setTimeout(()=>damageFlash.classList.remove('show'),120);audio.osc(72,.2,'sawtooth',.04,38);updateHUD();if(state.health<=0)endGame(false)}
  function dropCoin(z){if(z.coinDropped)return;z.coinDropped=true;const value=z.fresh?3+Math.floor(Math.random()*4):1+Math.floor(Math.random()*3),g=new THREE.Group();const mat=new THREE.MeshStandardMaterial({color:0xd4a72c,metalness:.82,roughness:.25,emissive:0x4b2d00,emissiveIntensity:.9});const coin=new THREE.Mesh(new THREE.CylinderGeometry(.23,.23,.065,20),mat);coin.rotation.x=Math.PI/2;g.add(coin);const ring=new THREE.Mesh(new THREE.TorusGeometry(.16,.025,8,18),new THREE.MeshBasicMaterial({color:0xffd86a}));g.add(ring);g.position.copy(z.model.position);g.position.y+=.35;g.userData.value=value;scene.add(g);coins.push(g)}
  function updateCoins(dt,now){for(let i=coins.length-1;i>=0;i--){const c=coins[i];c.rotation.y+=dt*2.8;c.position.y+=Math.sin(now*.004+c.id)*dt*.08;const d=c.position.distanceTo(player.position);if(d<2.3){c.position.lerp(player.position.clone().add(new THREE.Vector3(0,1,0)),Math.min(1,dt*7));if(d<.75){state.coins+=c.userData.value;state.chapterCoins+=c.userData.value;localStorage.setItem('ls-coins',String(state.coins));audio.coin();const pop=document.createElement('div');pop.className='coin-pop';pop.textContent=`+${c.userData.value} COINS`;hud.appendChild(pop);setTimeout(()=>pop.remove(),750);scene.remove(c);coins.splice(i,1);updateHUD()}}}}

  function zombieTargets(){const arr=[];for(const z of zombies)if(z.alive)z.model.traverse(o=>{if(o.isMesh)arr.push(o)});return arr}
  function killZombie(z){z.alive=false;z.deathTime=performance.now();state.kills++;dropCoin(z);z.action&&(z.action.timeScale=.2)}
  function fire(){if(state.mode!=='playing'||state.weapon!=='shotgun'||state.reloading||state.weaponSwitching)return;const now=performance.now();if(now-state.lastShot<760)return;if(state.clip<=0){audio.empty();reloadText.textContent=t('noAmmo');return}state.lastShot=now;state.clip--;state.shots++;audio.fire();const muzzle=shotgunView.userData.muzzle;if(muzzle){muzzle.intensity=55;setTimeout(()=>muzzle.intensity=0,45)}weaponRoot.rotation.x-=.13;weaponRoot.position.z+=.08;const targets=zombieTargets(),env=hospitalMeshes;for(let p=0;p<9;p++){const spread=.045,ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((Math.random()-.5)*spread,(Math.random()-.5)*spread),camera);ray.far=35;const zh=ray.intersectObjects(targets,false)[0],eh=ray.intersectObjects(env,false)[0];if(!zh||(eh&&eh.distance<zh.distance))continue;const idx=zh.object.userData.zombieIndex,z=zombies[idx];if(!z||!z.alive)continue;const damage=22+Math.random()*15;z.hp-=damage;z.alerted=true;state.hits++;audio.hurt(z,z.hp<=0);hitMarker.classList.remove('show');void hitMarker.offsetWidth;hitMarker.classList.add('show');if(z.hp<=0)killZombie(z)}for(const z of zombies)if(z.alive&&z.model.position.distanceTo(player.position)<28)z.alerted=true;updateHUD()}
  function swingAxe(){if(state.mode!=='playing'||state.weapon!=='hatchet'||state.axeSwinging)return;state.axeSwinging=true;audio.axe();const start=performance.now();const tick=()=>{const p=Math.min(1,(performance.now()-start)/430);hatchetView.rotation.set(-.16+Math.sin(p*Math.PI)*.7,.08-Math.sin(p*Math.PI)*.45,-.72+Math.sin(p*Math.PI)*1.15);if(p<1)requestAnimationFrame(tick);else{hatchetView.rotation.set(-.16,.08,-.72);state.axeSwinging=false}};tick();setTimeout(()=>{const forward=new THREE.Vector3(0,0,-1).applyQuaternion(camera.getWorldQuaternion(new THREE.Quaternion()));let best=null,bestD=2.35;for(const z of zombies){if(!z.alive)continue;const to=z.model.position.clone().add(new THREE.Vector3(0,1,0)).sub(camera.getWorldPosition(new THREE.Vector3())),d=to.length();if(d<bestD&&forward.dot(to.normalize())>.55&&hasLineOfSight(camera.getWorldPosition(new THREE.Vector3()),z.model.position.clone().add(new THREE.Vector3(0,1,0)))){best=z;bestD=d}}if(best){best.hp-=86;best.alerted=true;state.hits++;audio.hurt(best,best.hp<=0);if(best.hp<=0)killZombie(best)}},190)}
  function reload(){if(state.weapon!=='shotgun'||state.reloading||state.clip>=8||state.reserve<=0)return;state.reloading=true;audio.reload();updateHUD();setTimeout(()=>{const need=8-state.clip,take=Math.min(need,state.reserve);state.clip+=take;state.reserve-=take;state.reloading=false;updateHUD()},1350)}
  function switchWeapon(next){if(state.weapon===next||state.weaponSwitching)return;state.weaponSwitching=true;const start=performance.now(),base=weaponRoot.userData.baseY;const down=()=>{const p=Math.min(1,(performance.now()-start)/150);weaponRoot.position.y=base-p*.38;if(p<1)requestAnimationFrame(down);else{state.weapon=next;applyWeapon();const upStart=performance.now();const up=()=>{const q=Math.min(1,(performance.now()-upStart)/180);weaponRoot.position.y=base-.38+q*.38;if(q<1)requestAnimationFrame(up);else state.weaponSwitching=false};up()}};down()}

  function nearObjective(){return objectivePoints[state.stage]&&player.position.distanceTo(objectivePoints[state.stage])<2.3}
  function updateMission(){if(state.mode!=='playing'||state.stage>=6)return;marker.rotation.y+=.025;diamond.position.y=Math.sin(performance.now()*.003)*.18;if(state.stage===0&&nearObjective()){state.stage=1;showSubtitle('mara','sub1',4100);audio.objective();saveCheckpoint();updateObjective()}if([1,2,5].includes(state.stage)&&nearObjective()){interactPrompt.classList.add('show');interactText.textContent=state.stage===1?t('keycard'):state.stage===2?t('generator'):t('terminal')}else interactPrompt.classList.remove('show')}
  function interact(){if(state.mode!=='playing'||!nearObjective())return;if(state.stage===1){state.stage=2;showSubtitle('survivor','sub2',4000);audio.objective();saveCheckpoint();updateObjective()}else if(state.stage===2){audio.generator();state.stage=3;showSubtitle('system','sub3',4000);saveCheckpoint();updateObjective();spawnWave()}else if(state.stage===5){showSubtitle('system','sub6',4800);setTimeout(()=>endGame(true),1600)}}

  function openInventory(){if(state.mode!=='playing'||state.inventoryOpen)return;state.inventoryOpen=true;state.mode='inventory';document.exitPointerLock?.();inventoryOverlay.classList.remove('hidden');updateHUD()}
  function closeInventory(){if(!state.inventoryOpen)return;state.inventoryOpen=false;inventoryOverlay.classList.add('hidden');state.mode='playing';canvas.requestPointerLock?.()}
  function pause(){if(state.mode!=='playing')return;state.mode='paused';document.exitPointerLock?.();pauseOverlay.classList.remove('hidden')}
  function resume(){if(state.mode!=='paused')return;state.mode='playing';pauseOverlay.classList.add('hidden');canvas.requestPointerLock?.()}
  function restart(){location.reload()}
  function endGame(win){if(state.gameEnded)return;state.gameEnded=true;state.mode='ended';document.exitPointerLock?.();setViewVisible(false);resultOverlay.classList.remove('hidden');$('resultKicker').textContent=win?'MISSION COMPLETE':'MISSION FAILED';$('resultTitle').textContent=win?t('complete'):t('failed');$('resultText').textContent=win?t('completeText'):t('failedText');$('statKills').textContent=state.kills;$('statCoins').textContent=state.chapterCoins;const sec=Math.max(0,Math.floor((performance.now()-state.missionStart)/1000));$('statTime').textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;if(win){localStorage.setItem('ls-night-two-complete','true');localStorage.setItem('ls-chapter-02-complete','true');localStorage.setItem('ls-night-two-stage','6')}}

  function beginCinematic(){audio.init();audio.resume();state.mode='cinematic';state.cinematicStart=performance.now();storyGate.classList.add('hidden');cinematic.classList.remove('hidden');setViewVisible(false);skipBtn.disabled=true;skipCount.textContent='3';audio.startCar();cinemaText.textContent=t('intro1');audio.narrate(t('intro1'));setTimeout(()=>{if(state.mode==='cinematic'){cinemaText.textContent=t('intro2');audio.narrate(t('intro2'))}},5200);setTimeout(()=>{if(state.mode==='cinematic'){cinemaText.textContent=t('intro3');audio.narrate(t('intro3'))}},9800);setTimeout(()=>{if(state.mode==='cinematic'){cinemaKicker.textContent='SAINT MERCY HOSPITAL';cinemaTitle.textContent=lang==='ar'?'الوصول':'ARRIVAL';cinemaText.textContent=t('arrival1');audio.narrate(t('arrival1'))}},14000);setTimeout(()=>{if(state.mode==='cinematic'){cinemaText.textContent=t('arrival2');audio.narrate(t('arrival2'))}},17800)}
  function finishCinematic(){if(state.cinematicFinished)return;state.cinematicFinished=true;audio.stopCinema();cinemaFade.classList.add('show');setTimeout(()=>{cinematic.classList.add('hidden');cinemaFade.classList.remove('show');if(carRoot)carRoot.visible=false;state.mode='ready';startOverlay.classList.remove('hidden')},420)}
  function updateCinematic(now){const tms=(now-state.cinematicStart)/1000,front=hospitalBox.max.z,carStart=front+77,carEnd=front+8;if(carRoot){const p=THREE.MathUtils.smoothstep(Math.min(1,tms/14),0,1);carRoot.position.z=THREE.MathUtils.lerp(carStart,carEnd,p);carWheels.forEach(w=>w.rotation.x-=.12);audio.updateCar(Math.max(0,(carStart-carRoot.position.z)*.22))}if(tms<5){cinematicCamera.position.set(7,3.2,(carRoot?.position.z||carStart)+10);cinematicCamera.lookAt((carRoot?.position||new THREE.Vector3()).clone().add(new THREE.Vector3(0,1,0)))}else if(tms<10){cinematicCamera.position.set(-8,2.4,(carRoot?.position.z||front+30)+1);cinematicCamera.lookAt((carRoot?.position||new THREE.Vector3()).clone().add(new THREE.Vector3(0,1,0)))}else if(tms<14){cinematicCamera.position.set(4,2.1,front+18);cinematicCamera.lookAt(new THREE.Vector3(0,4,front-8))}else{const p=Math.min(1,(tms-14)/6);cinematicCamera.position.lerpVectors(new THREE.Vector3(10,5,front+16),new THREE.Vector3(0,3,front-4),p);cinematicCamera.lookAt(new THREE.Vector3(0,3,front-12))}const left=Math.max(0,3-Math.floor(tms));skipCount.textContent=left;if(tms>=3){skipBtn.disabled=false;skipBtn.innerHTML=lang==='ar'?'تخطي':'SKIP'}if(tms>=21)finishCinematic()}
  function startPlaying(){audio.init();audio.resume();state.mode='playing';state.missionStart=performance.now();startOverlay.classList.add('hidden');hud.classList.remove('hidden');setViewVisible(true);pointerHint.classList.remove('hidden');canvas.requestPointerLock?.();showSubtitle('survivor','sub0',3800);updateObjective();updateHUD()}

  function animateView(dt,now){weaponRoot.rotation.x=THREE.MathUtils.lerp(weaponRoot.rotation.x,0,dt*9);weaponRoot.position.z=THREE.MathUtils.lerp(weaponRoot.position.z,weaponRoot.userData.baseZ,dt*9);if(state.weapon==='shotgun'&&shotgunView.userData.muzzle)shotgunView.userData.muzzle.intensity*=.55;flashlight.visible=flashlightOn&&state.mode==='playing';mixers.forEach(m=>m.update(dt));scene.userData.fogCards?.forEach((m,i)=>{m.position.x+=Math.sin(now*.0002+i)*dt*.08})}
  function renderLoop(){const dt=Math.min(.04,clock.getDelta()),now=performance.now();if(state.mode==='cinematic')updateCinematic(now);if(state.mode==='playing'){movePlayer(dt);updateZombies(dt,now);updateCoins(dt,now);updateMission();if(now>state.subtitleUntil)subtitle.classList.remove('show')}animateView(dt,now);renderer.render(scene,state.mode==='cinematic'?cinematicCamera:camera);requestAnimationFrame(renderLoop)}

  function setupEvents(){addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight,false);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();cinematicCamera.aspect=camera.aspect;cinematicCamera.updateProjectionMatrix()});document.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='Escape'){if(state.inventoryOpen)closeInventory();else if(state.mode==='playing')pause();else if(state.mode==='paused')resume()}if(e.code==='KeyR')reload();if(e.code==='KeyE')interact();if(e.code==='Digit1')switchWeapon('shotgun');if(e.code==='Digit2')switchWeapon('hatchet');if(e.code==='KeyB'){state.inventoryOpen?closeInventory():openInventory()}if(e.code==='KeyF'){flashlightOn=!flashlightOn}if(e.code==='Space'&&state.mode==='cinematic'&&!skipBtn.disabled)finishCinematic()});document.addEventListener('keyup',e=>keys[e.code]=false);document.addEventListener('mousemove',e=>{if(document.pointerLockElement!==canvas||state.mode!=='playing')return;player.rotation.y-=e.movementX*.00225;pitch=THREE.MathUtils.clamp(pitch-e.movementY*.00195,-1.48,1.48);camera.rotation.x=pitch});document.addEventListener('pointerlockchange',()=>pointerHint.classList.toggle('hidden',document.pointerLockElement===canvas||state.mode!=='playing'));canvas.addEventListener('mousedown',e=>{if(e.button!==0)return;if(state.mode==='playing'&&document.pointerLockElement!==canvas){canvas.requestPointerLock?.();return}state.weapon==='shotgun'?fire():swingAxe()});canvas.addEventListener('wheel',e=>{if(state.mode!=='playing')return;e.preventDefault();switchWeapon(e.deltaY>0?'hatchet':'shotgun')},{passive:false});pointerHint.addEventListener('click',()=>canvas.requestPointerLock?.());startStoryBtn.addEventListener('click',beginCinematic);enterGame.addEventListener('click',startPlaying);skipBtn.addEventListener('click',()=>{if(!skipBtn.disabled)finishCinematic()});$('pauseBtn').addEventListener('click',pause);$('resumeBtn').addEventListener('click',resume);$('restartBtn').addEventListener('click',restart);$('replayBtn').addEventListener('click',restart);$('langBtn').addEventListener('click',()=>setLanguage(lang==='en'?'ar':'en'));closeInventoryBtn.addEventListener('click',closeInventory);inventoryShotgun.addEventListener('click',()=>{switchWeapon('shotgun');updateHUD()});inventoryHatchet.addEventListener('click',()=>{switchWeapon('hatchet');updateHUD()});addEventListener('blur',()=>{if(state.mode==='playing')pause()})}

  async function boot(){setLanguage(lang);loadProgress.style.width='4%';setupEvents();if(location.protocol==='file:'){loadText.textContent='Chapter Two needs the local server';loadDetail.textContent='Close this page and run start-local.bat, then open Chapter Two from the menu.';return}await loadAssets();sampleHospital();buildExterior();buildBody();buildWeapons();spawnInitial();state.stage=Math.max(0,Math.min(5,Number(localStorage.getItem('ls-night-two-stage')||0)));updateObjective();updateHUD();loadProgress.style.width='100%';loadText.textContent=t('ready');loadDetail.textContent=`Hospital ready · ${templates.old.length+templates.fresh.length} infected variants · ${walkPoints.length} mapped positions`;await new Promise(r=>setTimeout(r,500));loading.classList.add('hidden');storyGate.classList.remove('hidden');requestAnimationFrame(renderLoop)}
  boot().catch(err=>{console.error(err);loadText.textContent='Unable to load Chapter Two';loadDetail.textContent=err.message||String(err)});
})();
